language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7

# Install packages
install:
  - travis_retry pip install coveralls
  - travis_retry python setup.py install
 
# Run test
script:
  - nosetests --verbose --with-coverage --cover-branches --cover-package=narmer --logging-level=INFO --processes=1 --process-timeout=60 --process-restartworker
 
# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
