language: python
python:
  #- pypy
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  #- nightly
  #- pypy3  

# Install packages
install:
  - travis_retry pip install abydos
  - travis_retry pip install coveralls
  - travis_retry python setup.py install
 
# Run test
script:
  - nosetests --verbose --with-coverage --cover-branches --cover-package=narmer --logging-level=INFO
 
# Calculate coverage
after_success:
  - coveralls --verbose --rcfile=.coveragerc
